### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ArtemGoutsoul** [klesun/deep-assoc-completion#108]
plugin version:
2019.07.31.001
```
Worker exited due to exception

java.lang.NullPointerException
	at org.klesun.deep_assoc_completion.go_to_decl_providers.MainGoToDecl.truncateOnLineBreak(MainGoToDecl.java:72)
	at org.klesun.deep_assoc_completion.go_to_decl_providers.MainGoToDecl.lambda$null$8(MainGoToDecl.java:92)
	at org.klesun.lang.IIt.lambda$map$0(IIt.java:28)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.EndIterator.getCurrent(EndIterator.java:21)
	at org.klesun.lang.iterators.EndIterator.hasNext(EndIterator.java:41)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at org.klesun.lang.It.arr(It.java:113)
	at org.klesun.deep_assoc_completion.go_to_decl_providers.MainGoToDecl.getGotoDeclarationTargets(MainGoToDecl.java:95)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsFromProviders(GotoDeclarationAction.java:274)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:285)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:469)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:448)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$1500(CtrlMouseHandler.java:91)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.doExecute(CtrlMouseHandler.java:729)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2100(CtrlMouseHandler.java:646)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:700)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:936)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:231)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:229)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:37)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:180)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019
Licensed to Enkora Oy / Artem Goutsoul
Subscription is active until February 6, 2020
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 12
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.tooltip.initialDelay=187
Non-Bundled Plugins: CMD Support, Key Promoter X, Scratch, Statistic, String Manipulation, Jetbrains TeamCity Plugin, com.intellij.ideolog, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.csv, org.intellij.tasks.navigation, com.dmarcotte.handlebars, com.jetbrains.lang.ejs, NEON support, com.kalessil.phpStorm.phpInspectionsEA, lv.midiana.misc.phpstorm-plugins.deep-keys, lv.midiana.misc.idea-plugins.deep-js-completion, org.psliwa.idea.composer, ru.adelf.idea.dotenv, some.awesome

**Comment by klesun** [comment]
Thanks for the report

**Comment by klesun** [comment]
[2019.08.06.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/66716) - I did not find the root of the cause, but I added strict `@NotNull` annotations in the project for debug. Next time the stack trace will include the source of these `null`s and I'll be able to fix it. If you will be so kind to post it again, I will be very grateful ;)

**Comment by MisatoTremor** [comment]
2019.08.15.001

```
java.lang.NullPointerException
	at org.klesun.deep_assoc_completion.go_to_decl_providers.MainGoToDecl.truncateOnLineBreak(MainGoToDecl.java:73)
	at org.klesun.deep_assoc_completion.go_to_decl_providers.MainGoToDecl.lambda$null$9(MainGoToDecl.java:93)
	at org.klesun.lang.IIt.lambda$map$0(IIt.java:28)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.EndIterator.getCurrent(EndIterator.java:21)
	at org.klesun.lang.iterators.EndIterator.hasNext(EndIterator.java:41)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at org.klesun.lang.It.arr(It.java:113)
	at org.klesun.deep_assoc_completion.go_to_decl_providers.MainGoToDecl.getGotoDeclarationTargets(MainGoToDecl.java:96)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsFromProviders(GotoDeclarationAction.java:279)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:290)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:469)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:448)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$1500(CtrlMouseHandler.java:91)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.doExecute(CtrlMouseHandler.java:729)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2100(CtrlMouseHandler.java:646)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:700)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:936)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:231)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:229)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:37)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:180)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by klesun** [comment]
Thanks a lot!

**Comment by klesun** [comment]
[2019.08.28.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/67923)
Hope this will fix the issue for good

**Comment by klesun** [comment]
It should not, but, please, ping me if the issue happens again.
