### ISSUE TITLE
Exception when searching file

### ISSUE THREAD

**Issue by CZechBoY** [klesun/deep-assoc-completion#18]
Hopefully this tracebacks helps
```
java.lang.NullPointerException
	at org.klesun.deep_assoc_completion.entry.ShowDocs.actionPerformed(ShowDocs.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:621)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by klesun** [comment]
yikes, thank you very much, I'll fix this asap

**Comment by klesun** [comment]
Steps to reproduce: press Ctrl+Alt+Q or _Tools -> Show Deep Type_ when no files are opened.

**Comment by klesun** [comment]
Added a null check - now if you try to press Ctrl+Alt+Q with no file, a "There is no file opened to describe a php variable" message will appear. I wonder, whether just doing nothing would be better in such case...

Fix: 
c0db27a18cb3798965ef9ac88f7423359f2e2509
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/40929
