### ISSUE TITLE
java.lang.NoClassDefFoundError: com/jetbrains/php/lang/documentation/phpdoc/psi/PhpDocToken on PHPStorm startup

### ISSUE THREAD

**Issue by Edwinws** [klesun/deep-assoc-completion#183]
Getting this error after restarting PHPStorm

PHPStorm info: 
```
PhpStorm 2017.3.7
Build #PS-173.4674.69, built on December 4, 2018
JRE: 1.8.0_152-release-1024-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.8.0-7642-generic
```

Plugin version: 2019.04.22.001

```
com/jetbrains/php/lang/documentation/phpdoc/psi/PhpDocToken
java.lang.NoClassDefFoundError: com/jetbrains/php/lang/documentation/phpdoc/psi/PhpDocToken
	at org.klesun.deep_assoc_completion.entry.DeepAssocFirstCbtr.<init>(DeepAssocFirstCbtr.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
	at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
	at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
	at com.intellij.codeInsight.completion.CompletionPreloader.preload(CompletionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.jetbrains.php.lang.documentation.phpdoc.psi.PhpDocToken PluginClassLoader[lv.midiana.misc.phpstorm-plugins.deep-keys, 2019.04.22.001] com.intellij.ide.plugins.cl.PluginClassLoader@36c0d4a7
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
```

**Comment by klesun** [comment]
Wow, `2019.04.22.001` is pretty old version...

**Comment by klesun** [comment]
Sadly I don't have enough time to investigate the issues of 2-years old release issues, but if updating IDEA is absolutely not an option for you, please, reply, I'll reopen and try to think of possible solutions.
