### ISSUE TITLE
Again memory overflow $fareQuoteInfo['pricingList'][$i]['pricingBlockList'][$j]['']

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#22]
Should fix asap.

**Comment by klesun** [comment]
Simpler steps to reproduce:
`PqParser::parse()` - press _Ctrl + Alt + Q_ on `$pqList`

Got stack trace:
```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.addAll(ArrayList.java:583)
	at org.klesun.lang.Lang$ListWrapper.addAll(Lang.java:355)
	at org.klesun.lang.Lang$L.addAll(Lang.java:173)
	at org.klesun.lang.Lang$L.fap(Lang.java:254)
	at org.klesun.lang.Lang$L.fap(Lang.java:247)
	at org.klesun.deep_assoc_completion.resolvers.VarRes.lambda$addAssignment$5(VarRes.java:49)
	at org.klesun.deep_assoc_completion.resolvers.VarRes$$Lambda$1961/607499822.accept(Unknown Source)
	at org.klesun.lang.Lang$L.lambda$fch$3(Lang.java:274)
	at org.klesun.lang.Lang$L$$Lambda$1784/260919785.accept(Unknown Source)
	at org.klesun.lang.Lang$L.fch(Lang.java:280)
	at org.klesun.lang.Lang$L.fch(Lang.java:274)
	at org.klesun.deep_assoc_completion.resolvers.VarRes.addAssignment(VarRes.java:44)
	at org.klesun.deep_assoc_completion.resolvers.VarRes.lambda$assignmentsToTypes$6(VarRes.java:72)
	at org.klesun.deep_assoc_completion.resolvers.VarRes$$Lambda$1761/1686397549.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.klesun.deep_assoc_completion.resolvers.VarRes.assignmentsToTypes(VarRes.java:72)
	at org.klesun.deep_assoc_completion.resolvers.VarRes.resolve(VarRes.java:234)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.lambda$resolveIn$0(DeepTypeResolver.java:24)
	at org.klesun.deep_assoc_completion.DeepTypeResolver$$Lambda$1488/1658254103.apply(Unknown Source)
	at org.klesun.lang.Opt.map(Opt.java:32)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.resolveIn(DeepTypeResolver.java:24)
	at org.klesun.deep_assoc_completion.helpers.SearchContext.findExprType(SearchContext.java:84)
	at org.klesun.deep_assoc_completion.helpers.FuncCtx.findExprType(FuncCtx.java:51)
	at org.klesun.deep_assoc_completion.resolvers.MethCallRes.lambda$findPsiExprType$0(MethCallRes.java:32)
	at org.klesun.deep_assoc_completion.resolvers.MethCallRes$$Lambda$1955/231005371.apply(Unknown Source)
	at org.klesun.lang.Opt.map(Opt.java:32)
	at org.klesun.deep_assoc_completion.resolvers.MethCallRes.findPsiExprType(MethCallRes.java:32)
	at org.klesun.deep_assoc_completion.resolvers.MethCallRes.lambda$null$20(MethCallRes.java:96)
```
I knew the day would come when this "TODO: make it immutable" will tell me "I told you!"

**Comment by klesun** [comment]
I think this was completely caused by b5c4998d9f2a3739e865b08de04558acb7eb89d5. My theory is: since it treated _every_ function call as an `array_unshift`, we probably got random recursions here and there that could not be caught by the normal mechanism. I can't say for sure it was the case, but it does not reproduce anymore, so I think we can close our eyes and happily accept this theory.

**Comment by klesun** [comment]
... It reproduces again, see #28
If you run tests, you get OutOfMemory exception on `providePqParserNotArrayUnshiftMemoryOverflow` caused by `356929` types on `$headersLine`
