### ISSUE TITLE
$this->getSessionData()[''] in ProcessApolloTerminalInputAction.php causes memory overflow

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#28]
It first shows key names OK, but then memoryoverflows on attempt to retrieve detailed type info

**Comment by klesun** [comment]
The exception, by the way:
```
2018-01-15 00:26:38,752 [ 660533]  ERROR - on.CompletionProgressIndicator - Java heap space 
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.addAll(ArrayList.java:583)
	at org.klesun.lang.Lang$ListWrapper.addAll(Lang.java:502)
	at org.klesun.lang.Lang$L.addAll(Lang.java:231)
	at org.klesun.lang.Lang$L.fap(Lang.java:341)
	at org.klesun.lang.Lang$L.fap(Lang.java:334)
	at org.klesun.deep_assoc_completion.helpers.MultiType.getKey(MultiType.java:77)
	at org.klesun.deep_assoc_completion.completion_providers.DeepKeysPvdr.lambda$addCompletions$9(DeepKeysPvdr.java:140)
	at org.klesun.deep_assoc_completion.completion_providers.DeepKeysPvdr$$Lambda$2691/152308669.apply(Unknown Source)
	at org.klesun.lang.Lang$Dict.lambda$map$2(Lang.java:197)
	at org.klesun.lang.Lang$Dict$$Lambda$2528/1051175909.apply(Unknown Source)
	at org.klesun.lang.Lang$Dict.lambda$map$1(Lang.java:192)
	at org.klesun.lang.Lang$Dict$$Lambda$2529/533995266.apply(Unknown Source)
	at org.klesun.lang.Lang$L.lambda$map$1(Lang.java:280)
	at org.klesun.lang.Lang$L$$Lambda$1705/1916170994.apply(Unknown Source)
	at org.klesun.lang.Lang$L.map(Lang.java:288)
	at org.klesun.lang.Lang$L.map(Lang.java:280)
	at org.klesun.lang.Lang$Dict.map(Lang.java:192)
	at org.klesun.lang.Lang$Dict.map(Lang.java:197)
	at org.klesun.deep_assoc_completion.completion_providers.DeepKeysPvdr.addCompletions(DeepKeysPvdr.java:140)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:152)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:152)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
2018-01-15 00:26:38,756 [ 660537]  ERROR - on.CompletionProgressIndicator - IntelliJ IDEA 2017.3.2  Build #IU-173.4127.27 
2018-01-15 00:26:38,756 [ 660537]  ERROR - on.CompletionProgressIndicator - JDK: 1.8.0_151 
2018-01-15 00:26:38,757 [ 660538]  ERROR - on.CompletionProgressIndicator - VM: Java HotSpot(TM) 64-Bit Server VM 
2018-01-15 00:26:38,757 [ 660538]  ERROR - on.CompletionProgressIndicator - Vendor: Oracle Corporation 
2018-01-15 00:26:38,757 [ 660538]  ERROR - on.CompletionProgressIndicator - OS: Windows 7 
2018-01-15 00:26:38,758 [ 660539]  ERROR - on.CompletionProgressIndicator - Last Action: EditorDown 

```

**Comment by klesun** [comment]
Temporary workaround: 2b7e5e626e2024adbd748fbc908871d07f6dff78

The problem is: there are 7k duplicate types merged after circular reference resolution. Amount of types grows exponentially causing array being so big it results in Memory Overflow.

I'm not sure about the reasons of so many types. I want to think there is a bug somewhere. But it is possible that there is not a bug, just the price I have to pay for remembering what arguments you pass to the function. If it is the latter, some optimization must be made to eliminate duplicate types. 

My last thought was to cache resolution result per function/passed args at the moment we pass them. So when we get return type of func having 7000 duplicate types by passing an argument, first will resolve type using the argument, and rest 6999 will take it from cache (would be nice to eliminate them altogether though...).

**Comment by klesun** [comment]
Wait, wait, wait, just htough about something. DeepType is context-free, right? Since it only has _functions_ to get type from arguments, not result of these functions. That means, we can store the expression PSI and use it as unique key to get rid of duplicates, am I right?

**Comment by klesun** [comment]
I think I start to understand the problem. The 7000 types should actually be duplicates of each other, but I re-create them in `VarRes::assignmentsToTypes()`, that makes each of them unique.

What should be done - get rid of damn `addAssignment()` - treat each `$arr['key1']['key2'] = ...` assignment as equivalent of `$arr = ['key1' => ['key2' => ...]]`. I believe that's how it's done in the python version of plugin. Once it's done, it should become possible to filter duplicates in `new MultiType(...)` with something like `HashSet`.

I also think there one more thing that can be optimized - recursion detection. Currently I just don't go deeper if I notice that same sequence was repeated second time. Instead of that I should _break_ from this second sequence, returning `0` types. I'll post a scrap of unfinished code that does that in a branch.

**Comment by klesun** [comment]
The fix I decided to use is described in following text (hope it helps):

итак, идея: уникальность типа

- два типа идентичны если у них один PSI экспрешна (TODO: подумать что делать с типами без экспрешнов: array_map) и одинаковые FuncCtx
- два FuncCtx одинаковы если:
- 1. у них одинаковы PSI аргументов
- 2. у них одинаковы parent FuncCtx

правда возникает вопрос что считать типом:

if (rand() % 2) {
	$state = makeApolloState();
} else {
	$state = makeSabreState();
}
return addSessionIdToState($state);

сколько типов у $state переданного в addSessionIdToState()? 
Я бы сказал что два: аполловский и сейбровский.
Так что, ещё не уверен, но избавляться от дубликатных типов такми образом видимо не получится...
ЗАТО вызов addSessionIdToState($state) можно кешировать с помощью логики описаной выше... и вообще любого выражения... 
гм, а вообще, если мы их будем брать из кеша, вероятно какие-то дубликаты там всё-таки есть - те что с одного ключа в хеше, да?
