### ISSUE TITLE
Got null pointer exception on doc comment method completion

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#30]
Got it here:
```php
<?php
namespace Rbs\Process\Amadeus;

/** provides convenient functions to make SSR commands from data */
class SsrCmdMaker
{
    /** @param $nameRec = Amadeus */
    public static function makeDocsCmd($nameRec)
    {

    }
}
```

```
Argument for @NotNull parameter 't' of org/klesun/lang/Lang$ListWrapper.add must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 't' of org/klesun/lang/Lang$ListWrapper.add must not be null
	at org.klesun.lang.Lang$ListWrapper.$$$reportNull$$$0(Lang.java)
	at org.klesun.lang.Lang$ListWrapper.add(Lang.java)
	at org.klesun.lang.Lang$L.add(Lang.java:231)
	at org.klesun.lang.Tls.regex(Tls.java:90)
	at org.klesun.deep_assoc_completion.completion_providers.DocFqnPvdr.extractTypedFqnPart(DocFqnPvdr.java:52)
	at org.klesun.deep_assoc_completion.completion_providers.DocFqnPvdr.lambda$addCompletions$13(DocFqnPvdr.java:65)
	at org.klesun.lang.Opt.thn(Opt.java:68)
	at org.klesun.deep_assoc_completion.completion_providers.DocFqnPvdr.addCompletions(DocFqnPvdr.java:65)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:152)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:152)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:112)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:839)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:92)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:821)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.b(CompletionProgressIndicator.java:832)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by klesun** [comment]
c7b062501e4fc6949375343d323315d57715a248
