### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by ooghry** [klesun/deep-assoc-completion#54]
Hi there
Today I got this exception twice.
```
stachtrace.txt
java.lang.NumberFormatException: For input string: "4294967295"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.klesun.lang.Opt.map(Opt.java:46)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.lambda$null$42(DeepTypeResolver.java:100)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.lambda$resolveIn$43(DeepTypeResolver.java:98)
	at org.klesun.lang.It.frs(It.java:50)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.resolveIn(DeepTypeResolver.java:42)
	at org.klesun.deep_assoc_completion.helpers.SearchContext.findExprType(SearchContext.java:186)
	at org.klesun.deep_assoc_completion.helpers.ExprCtx.findExprType(ExprCtx.java:104)
	at org.klesun.deep_assoc_completion.resolvers.MiscRes.lambda$findPsiExprType$0(MiscRes.java:34)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.resolvers.MiscRes.findPsiExprType(MiscRes.java:34)
	at org.klesun.deep_assoc_completion.resolvers.MiscRes.lambda$resolve$17(MiscRes.java:86)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.resolvers.MiscRes.resolve(MiscRes.java:85)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.lambda$resolveIn$44(DeepTypeResolver.java:103)
	at org.klesun.lang.It.frs(It.java:50)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.resolveIn(DeepTypeResolver.java:42)
	at org.klesun.deep_assoc_completion.helpers.SearchContext.findExprType(SearchContext.java:186)
	at org.klesun.deep_assoc_completion.helpers.ExprCtx.findExprType(ExprCtx.java:104)
	at org.klesun.deep_assoc_completion.resolvers.var_res.AssRes.lambda$null$6(AssRes.java:77)
	at org.klesun.lang.Tls.lambda$onDemand$1(Tls.java:171)
	at org.klesun.deep_assoc_completion.resolvers.var_res.AssRes.makeType(AssRes.java:31)
	at org.klesun.deep_assoc_completion.resolvers.var_res.AssRes.lambda$assignmentsToTypes$2(AssRes.java:45)
	at org.klesun.lang.It.lambda$fap$8(It.java:154)
	at org.klesun.lang.iterators.FlatMapIterator.lambda$new$1(FlatMapIterator.java:18)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:26)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.MemoizingIterable$1.hasNext(MemoizingIterable.java:39)
	at org.klesun.lang.iterators.ThenIterator.hasNext(ThenIterator.java:19)
	at org.klesun.lang.MemoizingIterable$1.hasNext(MemoizingIterable.java:39)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:34)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:34)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:34)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:34)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.MemoizingIterable$1.hasNext(MemoizingIterable.java:39)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at org.klesun.lang.Lang.L(Lang.java:159)
	at org.klesun.deep_assoc_completion.helpers.Mt.getBriefValueText(Mt.java:156)
	at org.klesun.deep_assoc_completion.helpers.Mt.getBriefValueText(Mt.java:198)
	at org.klesun.deep_assoc_completion.completion_providers.DeepKeysPvdr.makeFullLookup(DeepKeysPvdr.java:139)
	at org.klesun.deep_assoc_completion.completion_providers.DeepKeysPvdr.lambda$addCompletions$19(DeepKeysPvdr.java:243)
	at org.klesun.lang.Dict.lambda$fch$4(Dict.java:38)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.klesun.lang.Dict.fch(Dict.java:38)
	at org.klesun.deep_assoc_completion.completion_providers.DeepKeysPvdr.addCompletions(DeepKeysPvdr.java:241)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:92)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:118)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:815)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:800)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:266)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:263)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```
induced.txt
Following exceptions happened soon after this one, most probably they are induced.


2018-11-12T20:38:14.340
java.lang.NumberFormatException: For input string: "4294967295"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.klesun.lang.Opt.map(Opt.java:46)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.lambda$null$42(DeepTypeResolver.java:100)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.lambda$resolveIn$43(DeepTypeResolver.java:98)
	at org.klesun.lang.It.frs(It.java:50)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.resolveIn(DeepTypeResolver.java:42)
	at org.klesun.deep_assoc_completion.helpers.SearchContext.findExprType(SearchContext.java:186)
	at org.klesun.deep_assoc_completion.helpers.ExprCtx.findExprType(ExprCtx.java:104)
	at org.klesun.deep_assoc_completion.resolvers.MiscRes.lambda$findPsiExprType$0(MiscRes.java:34)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.resolvers.MiscRes.findPsiExprType(MiscRes.java:34)
	at org.klesun.deep_assoc_completion.resolvers.MiscRes.lambda$resolve$17(MiscRes.java:86)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.resolvers.MiscRes.resolve(MiscRes.java:85)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.lambda$resolveIn$44(DeepTypeResolver.java:103)
	at org.klesun.lang.It.frs(It.java:50)
	at org.klesun.deep_assoc_completion.DeepTypeResolver.resolveIn(DeepTypeResolver.java:42)
	at org.klesun.deep_assoc_completion.helpers.SearchContext.findExprType(SearchContext.java:186)
	at org.klesun.deep_assoc_completion.helpers.ExprCtx.findExprType(ExprCtx.java:104)
	at org.klesun.deep_assoc_completion.resolvers.var_res.AssRes.lambda$null$6(AssRes.java:77)
	at org.klesun.lang.Tls.lambda$onDemand$1(Tls.java:171)
	at org.klesun.deep_assoc_completion.resolvers.var_res.AssRes.makeType(AssRes.java:31)
	at org.klesun.deep_assoc_completion.resolvers.var_res.AssRes.lambda$assignmentsToTypes$2(AssRes.java:45)
	at org.klesun.lang.It.lambda$fap$8(It.java:154)
	at org.klesun.lang.iterators.FlatMapIterator.lambda$new$1(FlatMapIterator.java:18)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:26)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.MemoizingIterable$1.hasNext(MemoizingIterable.java:39)
	at org.klesun.lang.iterators.ThenIterator.hasNext(ThenIterator.java:19)
	at org.klesun.lang.MemoizingIterable$1.hasNext(MemoizingIterable.java:39)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:34)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:34)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:34)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:34)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.MemoizingIterable$1.hasNext(MemoizingIterable.java:39)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at org.klesun.lang.Lang.L(Lang.java:159)
	at org.klesun.deep_assoc_completion.helpers.Mt.getBriefValueText(Mt.java:156)
	at org.klesun.deep_assoc_completion.helpers.Mt.getBriefValueText(Mt.java:198)
	at org.klesun.deep_assoc_completion.completion_providers.DeepKeysPvdr.makeFullLookup(DeepKeysPvdr.java:139)
	at org.klesun.deep_assoc_completion.completion_providers.DeepKeysPvdr.lambda$addCompletions$19(DeepKeysPvdr.java:243)
	at org.klesun.lang.Dict.lambda$fch$4(Dict.java:38)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.klesun.lang.Dict.fch(Dict.java:38)
	at org.klesun.deep_assoc_completion.completion_providers.DeepKeysPvdr.addCompletions(DeepKeysPvdr.java:241)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:92)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:118)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:815)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:800)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:266)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:263)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by klesun** [comment]
oh, thanks, I'll look what's wrong now
