### ISSUE TITLE
org.klesun.deep_assoc_completion.go_to_decl_providers.MainGoToDecl@a3784e2

### ISSUE THREAD

**Issue by ooghry** [klesun/deep-assoc-completion#59]
Hi 
PhpStorm 2018.2.6
Build #PS-182.5107.45, built on November 27, 2018
JRE: 1.8.0_152-release-1248-b22 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3
I got this error.

```
org.klesun.deep_assoc_completion.go_to_decl_providers.MainGoToDecl@a3784e2

java.lang.AbstractMethodError
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.update(GotoDeclarationAction.java:329)
	at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:232)
	at com.intellij.codeInsight.actions.CodeInsightAction.beforeActionPerformedUpdate(CodeInsightAction.java:73)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:168)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lastUpdateAndCheckDumb(ActionUtil.java:225)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:255)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:717)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by klesun** [comment]
Oh, thank you very much. I'll take a look in few hours.

**Comment by klesun** [comment]
Probably caused by this: https://github.com/JetBrains/intellij-community/commit/14f169e376ed96f7253d92ff13a30f6bf577f891

**Comment by klesun** [comment]
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/53511

**Comment by klesun** [comment]
Fixed.
Was broken for phpstorm versions before 183.5153.4 due to recent refactoring:
https://github.com/klesun/deep-assoc-completion/commit/2ef565301dd2fee1db83bbedbd5e13ad70fb02ba
Now it should work for any version.
