### ISSUE TITLE
java.lang.StackOverflowError on array_map

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#62]
Happens when I try to get completion in:
```php
$this->importPnr()['result']['pnrFields']['reservation']['passengers'][0]['nameNumber'][''];
```
With `ApolloPnrFieldsOnDemand::getReservation()` having all lines except last commented out.
```
java.lang.StackOverflowError
	at org.klesun.deep_assoc_completion.resolvers.FuncCallRes.lambda$array_map$13(Unknown Source)
	at org.klesun.deep_assoc_completion.structures.KeyType.lambda$mt$0(KeyType.java:26)
	at org.klesun.lang.Tls$OnDemand.get(Tls.java:195)
	at org.klesun.deep_assoc_completion.resolvers.FuncCallRes.lambda$null$12(Unknown Source)
	at org.klesun.lang.It.lambda$fap$8(It.java:154)
	at org.klesun.lang.iterators.FlatMapIterator.lambda$new$1(FlatMapIterator.java:18)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:26)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.It.has(It.java:283)
	at org.klesun.lang.It.def(It.java:220)
	at org.klesun.deep_assoc_completion.structures.KeyType.lambda$mt$0(KeyType.java:26)
	at org.klesun.lang.Tls$OnDemand.get(Tls.java:195)
	at org.klesun.deep_assoc_completion.resolvers.FuncCallRes.lambda$null$12(Unknown Source)
	at org.klesun.lang.It.lambda$fap$8(It.java:154)
	at org.klesun.lang.iterators.FlatMapIterator.lambda$new$1(FlatMapIterator.java:18)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:26)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.It.has(It.java:283)
	at org.klesun.lang.It.def(It.java:220)
	at org.klesun.deep_assoc_completion.structures.KeyType.lambda$mt$0(KeyType.java:26)
	at org.klesun.lang.Tls$OnDemand.get(Tls.java:195)
	at org.klesun.deep_assoc_completion.resolvers.FuncCallRes.lambda$null$12(Unknown Source)
	at org.klesun.lang.It.lambda$fap$8(It.java:154)
	at org.klesun.lang.iterators.FlatMapIterator.lambda$new$1(FlatMapIterator.java:18)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:26)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.It.has(It.java:283)
	at org.klesun.lang.It.def(It.java:220)
	at org.klesun.deep_assoc_completion.structures.KeyType.lambda$mt$0(KeyType.java:26)
        ...
	at org.klesun.lang.Tls$OnDemand.get(Tls.java:195)
	at org.klesun.deep_assoc_completion.resolvers.FuncCallRes.lambda$null$12(Unknown Source)
	at org.klesun.lang.It.lambda$fap$8(It.java:154)
	at org.klesun.lang.iterators.FlatMapIterator.lambda$new$1(FlatMapIterator.java:18)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:26)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.It.has(It.java:283)
	at org.klesun.lang.It.def(It.java:220)
	at org.klesun.deep_assoc_completion.structures.KeyType.lambda$mt$0(KeyType.java:26)
	at org.klesun.lang.Tls$OnDemand.get(Tls.java:195)
	at org.klesun.deep_assoc_completion.resolvers.FuncCallRes.lambda$null$12(Unknown Source)
	at org.klesun.lang.It.lambda$fap$8(It.java:154)
	at org.klesun.lang.iterators.FlatMapIterator.lambda$new$1(FlatMapIterator.java:18)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:26)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.It.has(It.java:283)
	at org.klesun.lang.It.def(It.java:220)
	at org.klesun.deep_assoc_completion.structures.KeyType.lambda$mt$0(KeyType.java:26)
	at org.klesun.lang.Tls$OnDemand.get(Tls.java:195)
	at org.klesun.deep_assoc_completion.helpers.Mt.lambda$getKeySt$6(Mt.java:109)
	at org.klesun.lang.L.lambda$flt$0(L.java:57)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:28)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.It.frs(It.java:51)
	at org.klesun.deep_assoc_completion.resolvers.MainRes.resolve(MainRes.java:62)
	at org.klesun.deep_assoc_completion.contexts.SearchCtx.findExprType(SearchCtx.java:201)
	at org.klesun.deep_assoc_completion.contexts.ExprCtx.findExprType(ExprCtx.java:116)
	at org.klesun.deep_assoc_completion.resolvers.ArrAccRes.lambda$resolve$0(ArrAccRes.java:25)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.resolvers.ArrAccRes.resolve(ArrAccRes.java:25)
	at org.klesun.deep_assoc_completion.resolvers.MainRes.lambda$null$18(MainRes.java:70)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.resolvers.MainRes.lambda$resolve$19(MainRes.java:70)
	at org.klesun.lang.It.frs(It.java:50)
	at org.klesun.deep_assoc_completion.resolvers.MainRes.resolve(MainRes.java:62)
	at org.klesun.deep_assoc_completion.contexts.SearchCtx.findExprType(SearchCtx.java:201)
	at org.klesun.deep_assoc_completion.contexts.ExprCtx.findExprType(ExprCtx.java:116)
	at org.klesun.deep_assoc_completion.completion_providers.AssocKeyPvdr.lambda$resolveAtPsi$3(AssocKeyPvdr.java:120)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.completion_providers.AssocKeyPvdr.resolveAtPsi(AssocKeyPvdr.java:120)
	at org.klesun.deep_assoc_completion.completion_providers.AssocKeyPvdr.addCompletions(AssocKeyPvdr.java:214)
```
Looks like there is an infinite circular reference between `k.keyType.getTypes.get()` in `FuncCallRes::array_map()` and `mtg.get()` in `KeyType::mt()`.

**Comment by klesun** [comment]
Reproduces only on one of my machines (and not on the two others) for some reason...

**Comment by klesun** [comment]
This is probably unrelated, but if you define arg type wih the name of this exact function in phpdoc, and hit _Ctrl+B_ twice, IDEA hangs. This is very bad.
