### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by martixy** [klesun/deep-assoc-completion#69]
Ah, the good old Null Pointer. Always fun to see one of those.
Was setting up a brand new symfony project and decided to try `->get('entity_manager')` to check if DB works and BAM.

```
2019-03-26T10:26:16.169
java.lang.NullPointerException
	at org.klesun.lang.Tls.findChildren(Tls.java:128)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.findUsedIndexes(UsageResolver.java:68)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.lambda$findArgTypeFromUsage$21(UsageResolver.java:84)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.findArgTypeFromUsage(UsageResolver.java:83)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.lambda$null$94(UsageResolver.java:309)
	at org.klesun.lang.IIt.lambda$fap$5(IIt.java:53)
	at org.klesun.lang.iterators.FlatMapIterator.lambda$new$1(FlatMapIterator.java:18)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:26)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.MemIt$1.hasNext(MemIt.java:38)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.MemIt$1.hasNext(MemIt.java:38)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.MemIt$1.hasNext(MemIt.java:38)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at org.klesun.lang.It.fch(It.java:134)
	at org.klesun.deep_assoc_completion.completion_providers.StrValsPvdr.addCompletions(StrValsPvdr.java:174)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:96)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:63)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:827)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:812)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:272)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:169)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:269)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


2019-03-26T10:26:16.390
java.lang.NullPointerException
	at org.klesun.lang.Tls.findChildren(Tls.java:128)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.findUsedIndexes(UsageResolver.java:68)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.lambda$findArgTypeFromUsage$21(UsageResolver.java:84)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.findArgTypeFromUsage(UsageResolver.java:83)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.lambda$null$94(UsageResolver.java:309)
	at org.klesun.lang.IIt.lambda$fap$5(IIt.java:53)
	at org.klesun.lang.iterators.FlatMapIterator.lambda$new$1(FlatMapIterator.java:18)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:26)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.MemIt$1.hasNext(MemIt.java:38)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.MemIt$1.hasNext(MemIt.java:38)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.MemIt$1.hasNext(MemIt.java:38)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at org.klesun.lang.It.fch(It.java:134)
	at org.klesun.deep_assoc_completion.completion_providers.StrValsPvdr.addCompletions(StrValsPvdr.java:174)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:96)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:63)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:827)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:812)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:272)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:169)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:269)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


2019-03-26T10:26:16.628
java.lang.NullPointerException
	at org.klesun.lang.Tls.findChildren(Tls.java:128)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.findUsedIndexes(UsageResolver.java:68)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.lambda$findArgTypeFromUsage$21(UsageResolver.java:84)
	at org.klesun.lang.Opt.lambda$fap$5(Opt.java:84)
	at org.klesun.lang.Opt.uni(Opt.java:158)
	at org.klesun.lang.Opt.fap(Opt.java:84)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.findArgTypeFromUsage(UsageResolver.java:83)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.lambda$null$94(UsageResolver.java:309)
	at org.klesun.lang.IIt.lambda$fap$5(IIt.java:53)
	at org.klesun.lang.iterators.FlatMapIterator.lambda$new$1(FlatMapIterator.java:18)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:26)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.MemIt$1.hasNext(MemIt.java:38)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.MemIt$1.hasNext(MemIt.java:38)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.MemIt$1.hasNext(MemIt.java:38)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:40)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:49)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at org.klesun.lang.It.fch(It.java:134)
	at org.klesun.deep_assoc_completion.completion_providers.StrValsPvdr.addCompletions(StrValsPvdr.java:174)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:96)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:63)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:827)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:812)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:272)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:169)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:269)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by klesun** [comment]
Yikes. Thanks for the report, will fix soon.

**Comment by klesun** [comment]
[2019.03.26.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/59951)
